import {
  Property,
  PropertyType,
  PropertyStatus,
  ListingType,
} from "@/types/property";

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Modern 4BR Home in Kabulonga",
    description: "Beautiful family home with pool and garden",
    propertyType: PropertyType.HOUSE,
    listingType: ListingType.SALE,
    price: 3800000,
    bedrooms: 4,
    bathrooms: 3,
    squareMeters: 280,
    address: "123 Leopards Hill Rd",
    neighborhood: "Kabulonga",
    city: "Lusaka",
    status: PropertyStatus.ACTIVE,
    images: [
      {
        id: "1",
        url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
        isPrimary: true,
        displayOrder: 0,
      },
    ],
    amenities: ["Pool", "Garden", "Parking", "Security"],
    features: ["Modern Kitchen", "Master Suite", "Guest Room"],
    userId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 150,
    isFeatured: true,
  },
  {
    id: "2",
    title: "Cozy 3BR in Rhodes Park",
    description: "Perfect starter home in quiet neighborhood",
    propertyType: PropertyType.HOUSE,
    listingType: ListingType.SALE,
    price: 2150000,
    bedrooms: 3,
    bathrooms: 2,
    squareMeters: 190,
    address: "45 Central Street",
    neighborhood: "Rhodes Park",
    city: "Lusaka",
    status: PropertyStatus.ACTIVE,
    images: [
      {
        id: "2",
        url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
        isPrimary: true,
        displayOrder: 0,
      },
    ],
    amenities: ["Parking", "Security", "Garden"],
    features: ["Modern Kitchen", "Open Plan Living", "Guest Bathroom"],
    userId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 85,
    isFeatured: false,
  },
  {
    id: "3",
    title: "Modern 3BR Family Home in Ibex Hill",
    description: "Spacious family home in desirable neighborhood",
    propertyType: PropertyType.HOUSE,
    listingType: ListingType.SALE,
    price: 1900000,
    bedrooms: 3,
    bathrooms: 2,
    squareMeters: 175,
    address: "Ibex Hill Road",
    neighborhood: "Ibex Hill",
    city: "Lusaka",
    status: PropertyStatus.ACTIVE,
    images: [
      {
        id: "3",
        url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800",
        isPrimary: true,
        displayOrder: 0,
      },
    ],
    amenities: ["Parking", "Security", "Garden"],
    features: ["Open Plan", "Modern Finishes", "Spacious Yard"],
    userId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 65,
    isFeatured: false,
  },
  {
    id: "4",
    title: "Compact 2BR Starter Home in Makeni",
    description: "Affordable starter home perfect for first-time buyers",
    propertyType: PropertyType.HOUSE,
    listingType: ListingType.SALE,
    price: 1500000,
    bedrooms: 2,
    bathrooms: 2,
    squareMeters: 120,
    address: "Makeni Main Road",
    neighborhood: "Makeni",
    city: "Lusaka",
    status: PropertyStatus.ACTIVE,
    images: [
      {
        id: "4",
        url: "https://images.unsplash.com/photo-1494203484021-3c454daf695d?w=800",
        isPrimary: true,
        displayOrder: 0,
      },
    ],
    amenities: ["Parking", "Security"],
    features: ["Modern Kitchen", "Compact Layout", "Low Maintenance"],
    userId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 120,
    isFeatured: false,
  },
  {
    id: "5",
    title: "Luxury 5BR Estate Home in Longacres",
    description: "Stunning luxury estate with premium finishes throughout",
    propertyType: PropertyType.HOUSE,
    listingType: ListingType.SALE,
    price: 4200000,
    bedrooms: 5,
    bathrooms: 4,
    squareMeters: 350,
    address: "Longacres Boulevard",
    neighborhood: "Longacres",
    city: "Lusaka",
    status: PropertyStatus.ACTIVE,
    images: [
      {
        id: "5",
        url: "https://images.unsplash.com/photo-1558036117-15d82a90b9b1?w=800",
        isPrimary: true,
        displayOrder: 0,
      },
    ],
    amenities: ["Pool", "Garden", "Gym", "Security", "Parking", "Solar Power"],
    features: [
      "Master Suite",
      "Home Office",
      "Entertainment Area",
      "Guest Wing",
    ],
    userId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 245,
    isFeatured: true,
  },
  {
    id: "6",
    title: "Beautiful 4BR Home in Olympia",
    description: "Well-maintained family home in established neighborhood",
    propertyType: PropertyType.HOUSE,
    listingType: ListingType.SALE,
    price: 2950000,
    bedrooms: 4,
    bathrooms: 3,
    squareMeters: 240,
    address: "Olympia Park Drive",
    neighborhood: "Olympia",
    city: "Lusaka",
    status: PropertyStatus.ACTIVE,
    images: [
      {
        id: "6",
        url: "https://images.unsplash.com/photo-1605146769289-440113cc3d00?w=800",
        isPrimary: true,
        displayOrder: 0,
      },
    ],
    amenities: ["Garden", "Security", "Parking", "Borehole"],
    features: ["Modern Kitchen", "Large Living Area", "Study Room"],
    userId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 98,
    isFeatured: false,
  },
  // Rental Properties
  {
    id: "7",
    title: "Spacious 3BR Apartment in Woodlands",
    description:
      "Modern apartment with great amenities, perfect for professionals or small families",
    propertyType: PropertyType.APARTMENT,
    listingType: ListingType.RENT,
    price: 8500,
    bedrooms: 3,
    bathrooms: 2,
    squareMeters: 145,
    address: "Woodlands Shopping Centre Area",
    neighborhood: "Woodlands",
    city: "Lusaka",
    status: PropertyStatus.ACTIVE,
    images: [
      {
        id: "7",
        url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
        isPrimary: true,
        displayOrder: 0,
      },
    ],
    amenities: ["Parking", "Security", "Generator", "Water Backup"],
    features: ["Open Plan Kitchen", "Balcony", "Built-in Wardrobes"],
    userId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 78,
    isFeatured: true,
  },
  {
    id: "8",
    title: "Luxury 2BR Penthouse in Mass Media",
    description: "Executive penthouse with stunning views and premium finishes",
    propertyType: PropertyType.APARTMENT,
    listingType: ListingType.RENT,
    price: 12000,
    bedrooms: 2,
    bathrooms: 2,
    squareMeters: 120,
    address: "Mass Media Area",
    neighborhood: "Mass Media",
    city: "Lusaka",
    status: PropertyStatus.ACTIVE,
    images: [
      {
        id: "8",
        url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
        isPrimary: true,
        displayOrder: 0,
      },
    ],
    amenities: ["Pool", "Gym", "Security", "Parking", "Generator", "Elevator"],
    features: ["Penthouse", "City Views", "Modern Kitchen", "Walk-in Closet"],
    userId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 132,
    isFeatured: true,
  },
  {
    id: "9",
    title: "Affordable 2BR Flat in Chelston",
    description:
      "Budget-friendly apartment in secure complex, ideal for young professionals",
    propertyType: PropertyType.APARTMENT,
    listingType: ListingType.RENT,
    price: 4500,
    bedrooms: 2,
    bathrooms: 1,
    squareMeters: 85,
    address: "Chelston Area",
    neighborhood: "Chelston",
    city: "Lusaka",
    status: PropertyStatus.ACTIVE,
    images: [
      {
        id: "9",
        url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
        isPrimary: true,
        displayOrder: 0,
      },
    ],
    amenities: ["Security", "Parking", "Water Backup"],
    features: ["Compact Layout", "Tiled Floors", "Kitchen Cabinets"],
    userId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 95,
    isFeatured: false,
  },
  {
    id: "10",
    title: "Family 4BR Townhouse in Sunningdale",
    description: "Spacious townhouse with garden, perfect for families",
    propertyType: PropertyType.TOWNHOUSE,
    listingType: ListingType.RENT,
    price: 15000,
    bedrooms: 4,
    bathrooms: 3,
    squareMeters: 220,
    address: "Sunningdale Residential Area",
    neighborhood: "Sunningdale",
    city: "Lusaka",
    status: PropertyStatus.ACTIVE,
    images: [
      {
        id: "10",
        url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800",
        isPrimary: true,
        displayOrder: 0,
      },
    ],
    amenities: ["Garden", "Security", "Parking", "Borehole", "Generator"],
    features: [
      "Master En-Suite",
      "Guest Toilet",
      "Study Room",
      "Servant Quarter",
    ],
    userId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 156,
    isFeatured: false,
  },
  {
    id: "11",
    title: "Modern 1BR Studio in Roma",
    description: "Compact studio apartment perfect for singles or students",
    propertyType: PropertyType.APARTMENT,
    listingType: ListingType.RENT,
    price: 3000,
    bedrooms: 1,
    bathrooms: 1,
    squareMeters: 45,
    address: "Roma Area",
    neighborhood: "Roma",
    city: "Lusaka",
    status: PropertyStatus.ACTIVE,
    images: [
      {
        id: "11",
        url: "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800",
        isPrimary: true,
        displayOrder: 0,
      },
    ],
    amenities: ["Security", "Parking"],
    features: ["Kitchenette", "Ensuite Bathroom", "Open Plan"],
    userId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 67,
    isFeatured: false,
  },
  {
    id: "12",
    title: "Executive 3BR Townhouse in Kabulonga",
    description:
      "Premium townhouse in prestigious neighborhood with excellent amenities",
    propertyType: PropertyType.TOWNHOUSE,
    listingType: ListingType.RENT,
    price: 18000,
    bedrooms: 3,
    bathrooms: 3,
    squareMeters: 200,
    address: "Kabulonga Extension",
    neighborhood: "Kabulonga",
    city: "Lusaka",
    status: PropertyStatus.ACTIVE,
    images: [
      {
        id: "12",
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
        isPrimary: true,
        displayOrder: 0,
      },
    ],
    amenities: [
      "Pool",
      "Garden",
      "Security",
      "Parking",
      "Generator",
      "Borehole",
    ],
    features: ["Modern Kitchen", "All En-Suite", "Laundry Room", "Patio"],
    userId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    viewCount: 189,
    isFeatured: true,
  },
];
